language: ruby

sudo: false

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - rvm: 2.2
      env: RUN=default TZ="/usr/share/zoneinfo/Pacific/Fiji"

    - rvm: 2.2
      env: RUN=rspec TILT_VERSION=2.0.1

    - rvm: 2.1
      env: RUN=rspec

    - rvm: 1.9.3
      env: RUN=rspec

    - rvm: 2.0.0
      env: RUN="rspec mspec_phantom"

    - rvm: rbx
      env: RUN=rspec

    - rvm: jruby
      env: RUN=rspec

    - rvm: jruby-head
      env: RUN=rspec

    - rvm: 2.2
      script:
        - npm install -g jshint
        - bundle exec rake lint

  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: rbx
    - rvm: jruby
    - rvm: jruby-head


before_install:
  # Keep track of which version of node and phantomjs we're running the specs against
  - node -v
  - phantomjs -v
  - git submodule update --init

script:
  - "bundle exec rake $RUN"

notifications:
  irc: "irc.freenode.org#opal"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2ea12333adebda0c2289

