language: ruby

sudo: required

dist: trusty

addons:
  chrome: stable

branches:
  only:
  - master
  - /^.*-stable$/
  - /^.*ci-check$/

cache:
  bundler: true
  directories:
    - /home/travis/.nvm/
    - smoke_test_opal_rspec

matrix:
  fast_finish: true

  include:
    - rvm: 2.5.1
      env: RUN=mspec_opal_chrome REINSTALL_BUNDLER=true

    - rvm: 2.5.1
      env: RUN=mspec_ruby_chrome REINSTALL_BUNDLER=true

    # - rvm: 2.5.1
    #   env:
    #     - RUN=browser_test
    #     - SAUCE_USERNAME=elia
    #     # SAUCE_ACCESS_KEY:
    #     - secure: GT13SjzU8vmqKIyY2LAXje+ndqevTsX/w71JkZHRLTrDUl0qcIod7xsfahbzGt2gOZPYZUkKiVaPoUenhc/YeJ2jTJVHeHY9UEl2II+3tOtuvp2jLadA//aBbsB6/09d7lIZMzpa93TL2R/SncPxugYW9v2o8o8Lwd2iIzowT/g=

    - rvm: 2.5.1
      env: RUN=lint REINSTALL_BUNDLER=true

    - rvm: 2.5.1
      env: RUN=mspec_opal_nodejs REINSTALL_BUNDLER=true

    - rvm: 2.5.1
      env: RUN=mspec_ruby_nodejs REINSTALL_BUNDLER=true TZ="/usr/share/zoneinfo/Pacific/Fiji"

    - rvm: 2.5.1
      env: RUN=minitest REINSTALL_BUNDLER=true

    - rvm: 2.5.1
      env: RUN=rspec RACK_VERSION='~> 2.0.0' CHECK_COVERAGE=true REINSTALL_BUNDLER=true

    - rvm: 2.5.1
      env: RUN=smoke_test REINSTALL_BUNDLER=true

    - rvm: ruby-head
      env: RUN=rspec REINSTALL_BUNDLER=true

    - rvm: 2.4.4
      env: RUN=rspec RACK_VERSION='~> 2.0.0' REINSTALL_BUNDLER=true

    - rvm: 2.3.7
      env: RUN=rspec

    - rvm: 2.2.10
      env: RUN=rspec TILT_VERSION=2.0.1 SPROCKETS_VERSION='~> 3.7'

    - rvm: 2.1.10
      env: RUN=rspec RACK_VERSION='< 2.0'

    - rvm: jruby-9.2.0.0
      env: RUN=rspec

    - rvm: jruby-head
      env: RUN=rspec

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: RUN=smoke_test


before_install:
  # Keep track of which version of node we're running the specs against
  - node -v
  - git submodule update --init
  - npm install -g jshint
  - npm install -g uglify-js
  - test $REINSTALL_BUNDLER && gem install bundler || true
  - type bundle || gem install bundler
  - bundle config without doc
  - which google-chrome-stable
  - google-chrome-stable --version
  - export RUBYOPT=-w
  # Wokraround from https://github.com/travis-ci/travis-ci/issues/9024#issuecomment-356282802
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

script:
  - "bundle exec rake $RUN"

notifications:
  irc: "irc.freenode.org#opal"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2ea12333adebda0c2289

# addons:
#   sauce_connect: true
