language: ruby

sudo: false

cache:
  bundler: true
  directories:
  - node_modules

matrix:
  fast_finish: true

  include:
    - rvm: 2.2
      env: RUN=default TZ="/usr/share/zoneinfo/Pacific/Fiji"

    - rvm: 2.1
      env: RUN=rspec

    - rvm: 1.9.3
      env: RUN=rspec

    - rvm: 2.0.0
      env: RUN="rspec mspec"

    - rvm: rbx
      env: RUN=rspec

    - rvm: jruby
      env: RUN=rspec

    - rvm: jruby-head
      env: RUN=rspec

  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: rbx
    - rvm: jruby
    - rvm: jruby-head


before_install:
  - git submodule update --init
  - npm install

script:
  - "bundle exec rake $RUN"

notifications:
  irc: "irc.freenode.org#opal"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2ea12333adebda0c2289

