version: '{build}'

skip_tags: true
# AppVeyor automatically skips the build if the commit contains [ci skip] or [skip ci]
#skip_commits:
#  message: /\[ci skip\]/

clone_depth: 10

environment:
  ruby_version: '23'

branches:
  only:
    - master
    - /.*-stable/
    - /.*/ci-check/

install:
  - git submodule update --init --recursive
  # Take default Ruby out of path
  - SET PATH=%PATH:C:\Ruby193\bin;=%
  # Add Ruby to path from build matrix
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - node --version
  - bundler --version
  - bundle

build: off

# TODO: add mspec_chrome and minitest_chrome once Chrome 60 will be released
test_script:
  - bundle exec rake rspec mspec_nodejs minitest_nodejs minitest_node_nodejs
