version: '{build}'

skip_tags: true

clone_depth: 10

environment:
  ruby_version: '25'
  nodejs_version: '12'

branches:
  only:
    - master
    - /.*-stable/
    - /.*/ci-check/

cache:
  - smoke_test_opal_rspec
  - node_modules
  - '%APPDATA%\npm-cache'

install:
  # Install node
  - ps: Install-Product node $env:nodejs_version
  # Take default Ruby out of path
  - SET PATH=%PATH:C:\Ruby193\bin;=%
  # Add Ruby to path from build matrix
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - node --version
  - bundler --version
  - bundle
  - ruby bin/git-submodule-fast-install
  - npm install jshint uglify-js source-map

build: off

# TODO: add mspec_chrome and minitest_chrome once Chrome 60 will be released
test_script:
  - bundle exec rake rspec mspec_nodejs minitest_nodejs minitest_node_nodejs
