name: build

on:
  push:
    branches:
      - master
      - '*-stable'
      - '*/ci-check'
  pull_request: {}

permissions:
  contents: read

jobs:
  rake:
    name: ${{ matrix.combo.name || matrix.combo.ruby }}
    env:
      DEFAULT_RUBY: '4.0'
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        combo:
          - name: lint
            command: bin/rake lint
          - name: smoke-test-linux-nodejs-22
            node: lts/jod
            command: bin/rake smoke_test
          - name: smoke-test-linux-nodejs-latest
            node: latest
            command: bin/rake smoke_test
          - name: mspec-linux-nodejs-22
            node: lts/jod
            command: bin/rake mspec_nodejs
          - name: mspec-linux-nodejs-latest
            node: latest
            command: bin/rake mspec_nodejs
          - name: mspec-macos-nodejs-latest
            node: latest
            command: bundle exec rake mspec_nodejs
            os: macos-latest
          - name: mspec-windows-nodejs-latest
            node: latest
            command: bundle exec rake mspec_nodejs
            os: windows-latest
          - name: minitest-linux-nodejs-22
            node: lts/jod
            command: bin/rake minitest_nodejs
          - name: minitest-linux-nodejs-latest
            node: latest
            command: bin/rake minitest_nodejs
          - name: mspec-chrome-130
            chrome: '130'
            command: bin/rake mspec_chrome
          - name: mspec-chrome-latest
            chrome: stable
            command: bin/rake mspec_chrome
          - name: mspec-edge-latest
            command: bundle exec rake mspec_edge
            os: windows-latest
          - name: mspec-firefox-128-esr
            firefox: '128.9.0esr'
            command: xvfb-run bin/rake mspec_firefox
          # this should be 'latest' below, but for ff > 140 see issue #2768
          - name: mspec-firefox-latest
            firefox: 'latest-esr'
            command: xvfb-run bin/rake mspec_firefox
          - name: mspec-safari-latest
            command: bundle exec rake mspec_safari
            os: macos-latest
          # - name: head-ruby
          #   ruby: head
          #   permissive: true
          - name: rspec-current-ruby
            ruby: '4.0'
          - name: rspec-previous-ruby
            ruby: '3.4'
          - name: rspec-older-ruby
            ruby: '3.3'
          - name: rspec-near-eol-ruby
            ruby: '3.2'
          # JRuby 10.0 does not work at all, JRuby 9.4 exhibits a SystemExit error
          # - name: rspec-jruby
          #   ruby: 'jruby'
          - name: truffleruby
            ruby: 'truffleruby'
          - name: rspec-windows
            command: bundle exec rake rspec
            os: windows-latest
          - name: rspec-macos
            command: bundle exec rake rspec
            os: macos-latest
          - name: timezone
            node: latest
            command: bin/rake mspec_nodejs TZ="Pacific/Fiji"
          - name: performance
            node: latest
            permissive: true
            fetchdepth: '0'
            command: bin/rake performance:compare
            # os: ryzen

    runs-on: ${{ matrix.combo.os || 'ubuntu-latest' }}
    continue-on-error: ${{ matrix.combo.permissive || false }}
    steps:
      - if: ${{ matrix.combo.chrome }}
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ matrix.combo.chrome }}
      - if: ${{ matrix.combo.firefox }}
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.combo.firefox }}
      - if: ${{ matrix.combo.node}}
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.combo.node }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ fromJSON(matrix.combo.fetchdepth || '1') }}
      - if: ${{ matrix.combo.os != 'ryzen' }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.combo.ruby || env.DEFAULT_RUBY }}
          bundler-cache: false
      - run: ruby bin/git-submodule-fast-install
      - run: bundle lock
      - uses: actions/cache@v4
        env:
          KEY_PREFIX: ${{ runner.os }}-${{ matrix.combo.ruby || env.DEFAULT_RUBY }}
        with:
          path: ./vendor/bundle
          key: ${{ env.KEY_PREFIX }}-gem-${{ github.ref }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ env.KEY_PREFIX }}-gem-${{ github.ref }}
            ${{ env.KEY_PREFIX }}-gem-master
            ${{ env.KEY_PREFIX }}-gem-
      - uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ github.ref }}
            ${{ runner.os }}-npm-master
            ${{ runner.os }}-npm-
      - run: yarn install
      - name: bundle install
        run: |
          bundle config path $PWD/vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle clean
      - name: set environment variables USE_STRICT
        if: ${{ matrix.combo.strict == 'true' }}
        run: |
          echo "USE_STRICT=true" >> $GITHUB_ENV
      - name: set environment variables CHROME_BINARY
        if: ${{ matrix.combo.chrome }}
        run: |
          echo "CHROME_BINARY=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
          echo "CHROME_OPTS=--no-sandbox" >> $GITHUB_ENV
      - name: set environment variables MOZILLA_FIREFOX_BINARY
        if: ${{ matrix.combo.firefox }}
        run: |
          echo "MOZILLA_FIREFOX_BINARY=${{ steps.setup-firefox.outputs.firefox-path }}" >> $GITHUB_ENV
      - run: ${{ matrix.combo.command || 'bin/rake rspec' }}
